"""cascade

Revision ID: 0de3d977f388
Revises: e4367957251b
Create Date: 2021-09-27 14:17:54.474694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de3d977f388'
down_revision = 'e4367957251b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_options_question_id_fkey', 'question_options', type_='foreignkey')
    op.create_foreign_key(None, 'question_options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_section_id_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_survey_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questions', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sections_survey_id_fkey', 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key('sections_survey_id_fkey', 'sections', 'surveys', ['survey_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_survey_id_fkey', 'questions', 'surveys', ['survey_id'], ['id'])
    op.create_foreign_key('questions_section_id_fkey', 'questions', 'sections', ['section_id'], ['id'])
    op.drop_constraint(None, 'question_options', type_='foreignkey')
    op.create_foreign_key('question_options_question_id_fkey', 'question_options', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
