"""ondelete-question-response

Revision ID: 4d7e867a6232
Revises: e4be84c10e1f
Create Date: 2021-10-16 04:15:21.028021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7e867a6232'
down_revision = 'e4be84c10e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_responses_question_id_fkey', 'question_responses', type_='foreignkey')
    op.create_foreign_key(None, 'question_responses', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_responses', type_='foreignkey')
    op.create_foreign_key('question_responses_question_id_fkey', 'question_responses', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
