"""added

Revision ID: 80d3f78ea181
Revises: 129dd2e2c81f
Create Date: 2021-09-06 17:04:38.604478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d3f78ea181'
down_revision = '129dd2e2c81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'user_id')
    # ### end Alembic commands ###
