"""nullable

Revision ID: cb5f8b923229
Revises: 78d78a7d23cb
Create Date: 2021-09-16 07:37:08.826836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5f8b923229'
down_revision = '78d78a7d23cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
