"""slug-added

Revision ID: e4367957251b
Revises: cb5f8b923229
Create Date: 2021-09-18 07:59:48.356988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4367957251b'
down_revision = 'cb5f8b923229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'survey_responses', ['slug'])
    op.add_column('surveys', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'surveys', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='unique')
    op.drop_column('surveys', 'slug')
    op.drop_constraint(None, 'survey_responses', type_='unique')
    op.drop_column('survey_responses', 'slug')
    # ### end Alembic commands ###
