"""ondelete

Revision ID: e4be84c10e1f
Revises: 0de3d977f388
Create Date: 2021-10-16 04:11:24.835045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4be84c10e1f'
down_revision = '0de3d977f388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('survey_responses_survey_id_fkey', 'survey_responses', type_='foreignkey')
    op.create_foreign_key(None, 'survey_responses', 'surveys', ['survey_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_responses', type_='foreignkey')
    op.create_foreign_key('survey_responses_survey_id_fkey', 'survey_responses', 'surveys', ['survey_id'], ['id'])
    # ### end Alembic commands ###
